import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read the CSV file
const csvPath = path.join(__dirname, '../data/hanzi-ranks.csv');
const tsPath = path.join(__dirname, '../data/characterRankData.ts');

const csvContent = fs.readFileSync(csvPath, 'utf-8');
const lines = csvContent.trim().split('\n');

// Skip header row and parse data
const characters = lines.slice(1)
  .map(line => {
    const [rank, character] = line.split(',').map(s => s.trim());
    if (!rank || !character || isNaN(parseInt(rank))) {
      return null;
    }
    return character;
  })
  .filter(Boolean); // Remove null entries

// Generate TypeScript content
const tsContent = `// This file is auto-generated from hanzi-ranks.csv
// Do not edit this file directly

// Characters are ordered by frequency rank (index + 1 = rank)
export const characterRankData: string[] = ${JSON.stringify(characters, null, 2)};
`;

// Write TypeScript file
fs.writeFileSync(tsPath, tsContent);
console.log(`Generated ${tsPath} with ${characters.length} characters`); 