import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read the CSV file
const csvPath = path.join(__dirname, '../data/hanzi-ranks.csv');
const tsPath = path.join(__dirname, '../data/characterRankData.ts');

const csvContent = fs.readFileSync(csvPath, 'utf-8');
const lines = csvContent.trim().split('\n');

// Skip header row and parse data
const data = lines.slice(1).map(line => {
  const [rank, character] = line.split(',');
  return [character.trim(), parseInt(rank.trim())];
});

// Generate TypeScript content
const tsContent = `// This file is auto-generated from hanzi-ranks.csv
// Do not edit this file directly

export const characterRankData: Array<[string, number]> = ${JSON.stringify(data, null, 2)};
`;

// Write TypeScript file
fs.writeFileSync(tsPath, tsContent);
console.log(`Generated ${tsPath} with ${data.length} character ranks`); 